### ISSUE TITLE
Where is uncropped data of BurstSR

### ISSUE THREAD

**Issue by greatlog** [goutamgmb/NTIRE22_BURSTSR#1]
The provided data of BurstSR are cropped. But the GT images of the validation set of Track1 should be uncropped. Where can I get this data?

**Comment by goutamgmb** [comment]
Hi,

The uncropped raw BurstSR dataset can be downloaded using the script https://github.com/goutamgmb/NTIRE22_BURSTSR/blob/main/scripts/download_raw_burstsr_data.py.
