### ISSUE TITLE
About training data in Track 1 Synthetic

### ISSUE THREAD

**Issue by rangoXTY** [goutamgmb/NTIRE22_BURSTSR#2]
In Track 1, can i use BurstSR dataset (cropped) in paper “Deep Burst Super-Resolution” to train my model? Or BurstSR dataset  is limited  to Track 2 real-world?
Look forward to reply, Thank you.

**Comment by goutamgmb** [comment]
Hi,

You can use the training split of the BurstSR dataset for training your models for Track 1.

**Comment by rangoXTY** [comment]
Got it, thanks for your reply
