### ISSUE TITLE
Submission issues on CodaLab

### ISSUE THREAD

**Issue by Magauiya** [goutamgmb/NTIRE22_BURSTSR#3]
Dear organizers,

In the Codalab , the competition phase had changed to "Testing", but here (github) the testing phase will start after 9 days. So:

1. What is the actual deadline of the challenge?
2. If the deadline is on 23rd of March, then can you please change it on Codalab and allow us submit results on a validation set?

Thank you!

**Comment by goutamgmb** [comment]
Hi,

Thanks for reporting the issue. I have updated the deadline on codalab now. You should be able to submit results on the validation set now.
