### ISSUE TITLE
Unable to submit the results

### ISSUE THREAD

**Issue by nanmehta** [goutamgmb/NTIRE22_BURSTSR#5]
![error_NTIRE_submission](https://user-images.githubusercontent.com/67276550/160268935-7ba14969-df3b-44dd-a207-89f4cdf1eb98.PNG)
Hi,
While uploading the results, I am getting this error, kindly let me know where I am doing wrong

**Comment by goutamgmb** [comment]
Hi,

We do not have the submission on codalab for the test phase. Instead you need to submit your raw results using the google form. Please check https://github.com/goutamgmb/NTIRE22_BURSTSR#final-submission for details.

Regards
Goutam
